/* ===============================================================================
AGGREGATE FUNCTIONS PRACTICE
Concepts Covered:
- COUNT()
- SUM()
- AVG()
- MAX()
- MIN()
- GROUP BY
- HAVING
- DATE_TRUNC()
- Revenue Calculations
- NULL Handling in Aggregations
=============================================================================== */

-- =============================================================================
-- TABLE CREATION
-- =============================================================================
CREATE TABLE sales_agg (
             order_id      INT,
             customer_name VARCHAR(50),
             city          VARCHAR(50),
             order_date    DATE,
             quantity      INT,
             price         NUMERIC(10,2)
);

-- =============================================================================
-- SAMPLE DATA INSERTION
-- =============================================================================
INSERT INTO sales_agg (order_id, customer_name, city , order_date, quantity, price)  VALUES
(1,'Aman','Delhi','2024-01-10',2,500),
(2,'Riya','Mumbai','2024-01-15',1,1200),
(3,'Kabir','Pune','2024-02-05',3,400),
(4,'Sneha','Delhi','2024-02-20',NULL,800),
(5,'Arjun','Jaipur','2024-02-25',2,NULL),
(6,'Neha','Mumbai','2024-03-01',1,700),
(7,'Rahul','Pune','2024-03-10',5,150),
(8,'Pooja','Delhi','2024-03-15',NULL,900),
(9,'Karan','Bangalore','2024-03-20',4,300),
(10,'Meera','Chennai','2024-04-01',2,450);

-- =============================================================================
-- VIEW TABLE DATA
-- =============================================================================
SELECT * 
FROM sales_agg;

-- =============================================================================
-- AGGREGATE FUNCTION PRACTICE TASKS
-- =============================================================================
-- =============================================================================
-- BASIC AGGREGATIONS
-- =============================================================================

-- Task 1 — Calculate Total Orders
-- Find the total number of orders

SELECT COUNT(*) AS total_orders
FROM sales_agg;

-- =============================================================================
-- REVENUE ANALYSIS
-- =============================================================================

-- Task 2 — Calculate Total Revenue
-- Formula: quantity * price
-- Handle NULL values using COALESCE()

SELECT 
      SUM(COALESCE(quantity,0) * COALESCE(price,0)) AS total_revenue
FROM sales_agg;

-- Task 3 — Calculate Average Order Value
-- Find the average revenue generated per order

SELECT 
      AVG(COALESCE(quantity,0) * COALESCE(price,0)) AS avg_order_value
FROM sales_agg;

-- Task 4 — Find Maximum and Minimum Prices
-- Retrieve the highest and lowest product prices

SELECT
      MAX(price) AS highest_price,
	  MIN(price) AS lowest_price
FROM sales_agg;

-- =============================================================================
-- GROUP BY ANALYSIS
-- =============================================================================
-- Task 5 — Calculate City-wise Order Counts
-- Output Columns: city, total_orders

SELECT 
      city,
      COUNT(*) AS total_orders
FROM sales_agg
GROUP BY city;

-- Task 6 — Calculate City-wise Revenue
-- Find total revenue generated by each city

SELECT 
      city,
      SUM(COALESCE(quantity,0) * COALESCE(price,0)) AS total_revenue
FROM sales_agg
GROUP BY city;

-- =============================================================================
-- DATE-BASED AGGREGATIONS
-- =============================================================================

-- Task 7 — Calculate Monthly Order Counts
-- Hint: Use DATE_TRUNC('month', order_date)

SELECT 
      DATE_TRUNC('month', order_date) AS order_month,
      COUNT(*) AS total_orders
FROM sales_agg
GROUP BY month
ORDER BY month;

-- Task 8 — Calculate Monthly Revenue

SELECT 
      DATE_TRUNC('month', order_date) AS order_month,
      SUM(COALESCE(quantity,0) * COALESCE(price,0)) AS total_revenue
FROM sales_agg
GROUP BY month
ORDER BY month;

-- =============================================================================
-- HAVING CLAUSE ANALYSIS
-- =============================================================================

-- Task 9 — Filter Cities Using HAVING
-- Retrieve cities where total revenue exceeds 1000

SELECT 
      city,
      SUM(COALESCE(quantity,0) * COALESCE(price,0)) AS total_revenue
FROM sales_agg
GROUP BY city
HAVING SUM(COALESCE(quantity,0) * COALESCE(price,0)) > 1000;

-- =============================================================================
-- COUNT FUNCTION ANALYSIS
-- =============================================================================

-- Task 10 — Compare COUNT(*) and COUNT(column)
-- Understand the difference between total row counts and non-NULL value counts

SELECT 
      COUNT(*) AS total_rows,
      COUNT(quantity) AS non_null_quantity
FROM sales_agg;